# Generated by Django 2.0.1 on 2018-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='citystatezip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
